config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('src.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('src.commons.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('src.api.urls')),
    url(r'^gestion/', include('src.commons.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

src/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url, include
from src.api.views.user_views import ApiUserDetailView


urlpatterns = [
    url(
        regex=r'^user/cities$',
        view=ApiUserDetailView.user_cities,
        name='user_cities'
    ),
]

src/commons/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.summary_trips,
        name='summary_trips'
    ),
]

src/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

src/api/models.py
# -*- coding: utf-8 -*-

src/commons/models.py
# -*- coding: utf-8 -*-

src/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

@python_2_unicode_compatible
class User(AbstractUser):

    name = models.CharField(_('Nombre completo'), max_length=512)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    class Meta:
        verbose_name = 'Usuario'

@python_2_unicode_compatible
class City(models.Model):

    name = models.CharField(_('Nombre'), max_length=255)
    latitude = models.CharField(_('Latitud'), max_length=255)
    longitude = models.CharField(_('Longitud'), max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ciudades'


#@receiver(models.signals.pre_save, sender=UserApp)
def update_file_from_s3(sender, instance, using, **kwargs):
    try:
        if sender.objects.filter(id = instance.pk).exists():
            old = sender.objects.get(pk=instance.pk)
            if old.picture != instance.picture:
                old.picture.delete(save=False)
    except Exception as e:
        print (e)


#@receiver(models.signals.post_delete, sender=UserApp)
def remove_file_from_s3(sender, instance, using, **kwargs):
    instance.picture.delete(save=False)

src/api/views/user_views.py
# -*- coding: utf-8 -*-
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView

from src.api.serializers.user_serializer import CitySerializer
from src.users.models import City


class ApiUserDetailView(APIView):

    @api_view(['GET'])
    def user_cities(request):
        """
        Return group list registered in the system.
        """
        cities = City.objects.all().order_by('id')
        serializer = CitySerializer(cities, many=True)
        return Response(serializer.data)

src/commons/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

@login_required
def summary_trips(request, template_name='dashboard/summary.html'):
    data = {
        'green_trips': [],
        'yellow_trips': [],
        'red_trips': []
    }
    return render(request, template_name, data)

src/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import random

from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('summary_trips')


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

src/templates/dashboard/base.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="es" class="no-js">
  <head>
    <meta charset="utf-8">
    <title>Hackaton</title>
    <meta http-equiv="Refresh" content="30">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="description" content="Administración Hackaton - Hackaton">
    <meta name="author" content="Jhon Vergara">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Your stuff: Third-party css libraries go here -->
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700|Raleway:400,100,200,300,500,600,700,800,900/" />

    {% compress css %}
    <!-- This file store project specific CSS -->
    <link type="text/css" rel="stylesheet" href="{% static 'fonts/clip-font.min.css' %}" />

    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/perfect-scrollbar/css/perfect-scrollbar.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/sweetalert/dist/sweetalert.css' %}" />

    <link type="text/css" rel="stylesheet" href="{% static 'css/main.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/main-responsive.min.css' %}" />
    <link type="text/css" rel="stylesheet" media="print" href="{% static 'css/print.min.css' %}" />
    <link type="text/css" rel="stylesheet" id="skin_color" href="{% static 'css/theme/light.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/general.css' %}" />

    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/bootstrap-modal/css/bootstrap-modal-bs3patch.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/bootstrap-modal/css/bootstrap-modal.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/datatables/media/css/dataTables.bootstrap.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/fullcalendar/dist/fullcalendar.min.css' %}" />
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <!-- start: HEADER -->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <!-- start: TOP NAVIGATION CONTAINER -->
        <div class="container">
            <div class="navbar-header" style="margin-top: 3px;">
                <!-- start: RESPONSIVE MENU TOGGLER -->
                <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                <span class="clip-list-2"></span>
            </button>
                <!-- end: RESPONSIVE MENU TOGGLER -->
                <!-- start: LOGO -->
                <!-- end: LOGO -->
            </div>
            <div class="navbar-tools">
                <!-- start: TOP NAVIGATION MENU -->
                <ul class="nav navbar-right">
                    <!-- start: USER DROPDOWN -->
                    <li class=" current-user">
                        <a href="{% url 'account_logout' %}">
                            <span class="username">Salir</span>
                        </a>
                    </li>
                        <!-- end: USER DROPDOWN -->
                </ul>
                <!-- end: TOP NAVIGATION MENU -->
            </div>

            <h2 style="font-size: 18px;color: #C7C7C7;font-weight: bold;float: left;display: block;height: auto;margin-top: -30px;font-family: fantasy;text-align: center;width: 100%;">
              Hackaton.com
            </h2>

        </div>
        <!-- end: TOP NAVIGATION CONTAINER -->
    </div>
    <!-- end: HEADER -->
    <!-- start: MAIN CONTAINER -->
    <div class="main-container" >

        <!-- start: PAGE -->
        <div class="main-content" style="margin-left: 0px;">

            <!-- end: SPANEL CONFIGURATION MODAL FORM -->
            <div class="container">
                <!-- start: PAGE HEADER -->
                <div class="row">
                    <div class="col-sm-12">
                        <!-- start: PAGE TITLE & BREADCRUMB -->
                        <ol class="breadcrumb">
                            <li>
                                <i class="clip-file"></i>
                                <a href="/dashboard/">
                                    Resumen de Viajes
                                </a>
                            </li>
                            {% if breadcrumb %}
                            <li>
                                <i class="clip-file"></i>
                                <a href="">
                                    {{ breadcrumb.name }}
                                </a>
                            </li>
                            {% endif %}
                            <li class="active">
                                {{primary_title}}
                            </li>
                        </ol>
                        <div class="page-header">
                            <h1>
                              {% block primary_title %}{% endblock primary_title %}
                              <small>{% block secondary_title %}{% endblock secondary_title %}</small>
                            </h1>
                        </div><!-- end: PAGE TITLE & BREADCRUMB -->
                    </div>
                </div>
                <!-- end: PAGE HEADER -->
                {% if success_message %}
                  <div class="alert alert-success">
                      <button data-dismiss="alert" class="close">
                          &times;
                      </button>
                      <i class="fa fa-check-circle"></i>
                      <strong>Genial!</strong> {{success_message}}
                  </div>
                {% endif %}

                {% if info_message %}
                  <div class="alert alert-info">
                      <button data-dismiss="alert" class="close">
                          &times;
                      </button>
                      <i class="fa fa-info-circle"></i>
                      <strong>Información!</strong> {{info_message}}
                  </div>
                {% endif %}

                {% if warning_message %}
                  <div class="alert alert-warning">
                      <button data-dismiss="alert" class="close">
                          &times;
                      </button>
                      <i class="fa fa-exclamation-triangle"></i>
                      <strong>Cuidado!</strong> {{warning_message}}
                  </div>
                {% endif %}

                {% if error_message %}
                  <div class="alert alert-danger">
                      <button data-dismiss="alert" class="close">
                          &times;
                      </button>
                      <i class="fa fa-times-circle"></i>
                      <strong>Ojo!</strong> {{error_message}}
                  </div>
                {% endif %}
                <!-- start: PAGE CONTENT -->
                {% block main %}{% endblock main %}

                {% block inner %}{% endblock inner %}
                <!-- end: PAGE CONTENT-->
            </div>
        </div>
        <!-- end: PAGE -->
    </div>
    <!-- end: MAIN CONTAINER -->
    <!-- start: FOOTER -->
    <div class="footer clearfix">
        <div class="footer-inner">
            <script>
                document.write(new Date().getFullYear())
            </script> &copy; Todos los derechos reservados.
        </div>
        <div class="footer-items">
            <span class="go-top"><i class="clip-chevron-up"></i></span>
        </div>
    </div>
    <!-- end: FOOTER -->

    <div id="ajax-modal" class="modal fade" tabindex="-1" style="display: none;"></div>

    {% block javascript %}

      <!--<![endif]-->
      <script type="text/javascript" src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/blockUI/jquery.blockUI.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/perfect-scrollbar/js/min/perfect-scrollbar.jquery.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/jquery.cookie/jquery.cookie.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/sweetalert/dist/sweetalert.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'bower_components/jquery-validation/dist/jquery.validate.min.js' %}"></script>

      <script src="{% static 'bower_components/bootbox.js/bootbox.js' %}"></script>
      <script src="{% static 'bower_components/jquery-mockjax/dist/jquery.mockjax.min.js' %}"></script>
      <script src="{% static 'bower_components/select2/dist/js/select2.min.js' %}"></script>
      <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
      <script src="{% static 'bower_components/datatables/media/js/dataTables.bootstrap.js' %}"></script>
      <script src="{% static 'js/min/table-data.min.js' %}"></script>

      <script src="{% static 'bower_components/bootstrap-modal/js/bootstrap-modal.js' %}"></script>
      <script src="{% static 'bower_components/bootstrap-modal/js/bootstrap-modalmanager.js' %}"></script>
      <script src="{% static 'js/min/ui-modals.min.js' %}"></script>

      <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
      <script src="{% static 'bower_components/jqueryui-touch-punch/jquery.ui.touch-punch.min.js' %}"></script>
    <script src="{% static 'plugin/jquery-ui.custom.min.js' %}"></script>

      <script type="text/javascript" src="{% static 'js/min/main.min.js' %}"></script>
      <script src="{% static 'js/min/login.min.js' %}"></script>


      <script>
          jQuery(document).ready(function() {
              Main.init();
              Login.init();
              TableData.init();
              UIModals.init();
          });
      </script>
      {% compress js %}

      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>

src/templates/dashboard/generic/generic_form.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block title %} {{primary_title}} {% endblock %}
{% block primary_title %} {{primary_title}} {% endblock %}
{% block secondary_title %} {{secondary_title}} {% endblock %}

{% block main %}
    <form class="form-horizontal" method="post"  enctype="multipart/form-data">

        <div class="row">
            <div class="col-sm-12">
                <!-- start: TEXT FIELDS PANEL -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-external-link-square"></i> {{primary_title}}
                        <div class="panel-tools">
                            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
                            </a>
                            <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="btn btn-xs btn-link panel-refresh" href="#">
                                <i class="fa fa-refresh"></i>
                            </a>
                            <a class="btn btn-xs btn-link panel-expand" href="#">
                                <i class="fa fa-resize-full"></i>
                            </a>
                            <a class="btn btn-xs btn-link panel-close" href="#">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <form role="form" class="form-horizontal" enctype="multipart/form-data">
                            <p>{{ form.fieldname.errors.as_text }}</p>

                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                    </div>
                </div>
                <!-- end: TEXT FIELDS PANEL -->
            </div>
        </div>

    </form>
{% endblock %}

src/templates/dashboard/summary.html
{% extends "dashboard/base.html" %}
{% load static %}{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} {{primary_title}} {% endblock %}
{% block primary_title %} {{primary_title}} {% endblock %}
{% block secondary_title %} {{secondary_title}} {% endblock %}

{% block main %}
<style>
  .trip_detail{
        background: #cbd7ea !important;
  }
</style>
  <div class="row">

      <div class="col-sm-12">

          <table class="table table-striped table-bordered table-hover table-full-width" id="">
            <thead>
                <tr>
                    <th style="background-color: #25a033;color: white;text-align: center;font-size: 25px;">
                      Mayor a 1 km
                    </th>
                    <th style="background-color: #eacc09;color: white;text-align: center;font-size: 25px;">
                      Menor a 1 km
                    </th>
                    <th style="background-color: #FF4136;color: white;text-align: center;font-size: 25px;">
                      Viaje finalizado
                    </th>
                </tr>
            </thead>
            <tbody>
              <tr>
                <td style="font-size: 18px; text-align: center;vertical-align: top;">
                  <table class="table table-striped table-bordered table-hover table-full-width" >
                    {% for trip in green_trips %}
                      <tr>
                        <td onclick="show_trip_detail('trip_detail_{{trip.id}}');">
                          <div style="display: inline-block;background: #eec713;padding: 5px;font-size: 25px;text-transform: uppercase;">
                            {{trip.plate}}
                          </div>

                        </td>
                      </tr>
                      <tr id="trip_detail_{{trip.id}}" class="trip_detail" style="display: none;">
                        <td colspan="7">
                            <nav class="text-center" style="font-size: 25px;">
                                Conductor: {{ trip.driver.name }} <br/>
                                {% for passenger in trip.get_passengers %}
                                  Pasajero: {{passenger.userApp.name }} <br/>
                                {% endfor %}
                            </nav>
                        </td>
                      </tr>
                    {% endfor %}
                  </table>
                </td>
                <td style="font-size: 18px; text-align: center;vertical-align: top;">
                  <table class="table table-striped table-bordered table-hover table-full-width" >
                    {% for trip in yellow_trips %}
                      <tr>
                        <td onclick="show_trip_detail('trip_detail_{{trip.id}}');">
                          <div style="display: inline-block;background: #eec713;padding: 5px;font-size: 25px;text-transform: uppercase;">
                            {{trip.plate}}
                          </div>
                        </td>
                      </tr>
                      <tr id="trip_detail_{{trip.id}}" class="trip_detail" style="display: none;">
                        <td colspan="7">
                            <nav class="text-center" style="font-size: 25px;">
                                Conductor: {{ trip.driver.name }} <br/>
                                {% for passenger in trip.get_passengers %}
                                  Pasajero: {{passenger.userApp.name }} <br/>
                                {% endfor %}
                            </nav>
                        </td>
                      </tr>
                    {% endfor %}
                  </table>
                </td>
                <td style="font-size: 18px; text-align: center;vertical-align: top;">
                  <table class="table table-striped table-bordered table-hover table-full-width" >
                    {% for trip in red_trips %}
                      <tr>
                        <td onclick="show_trip_detail('trip_detail_{{trip.id}}');">
                          <div style="display: inline-block;background: #eec713;padding: 5px;font-size: 25px;text-transform: uppercase;">
                            {{trip.plate}}
                          </div>
                        </td>
                      </tr>
                      <tr id="trip_detail_{{trip.id}}" class="trip_detail" style="display: none;">
                        <td colspan="7">
                            <nav class="text-center" style="font-size: 25px;">
                                Fecha fin: {{ trip.end_time|date:'Y-m-d H:i' }} <br/>
                                Conductor: {{ trip.driver.name }} <br/>
                                {% for passenger in trip.get_passengers %}
                                  Pasajero: {{passenger.userApp.name }} <br/>
                                {% endfor %}
                            </nav>
                        </td>
                      </tr>
                    {% endfor %}
                  </table>
                </td>
              </tr>
            </tbody>
          </table>

      </div>
  </div>
<script>

  function show_trip_detail(id){
	  if($("#"+id).is(':visible')) {
        $("#"+id).hide('slow');
    }else{
        $("#"+id).show('slow');
    }

	}
</script>
{% endblock %}

src/templates/pages/about.html
{% extends "base.html" %}

src/templates/pages/home.html
{% extends "admin/base.html" %}

src/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

src/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

src/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}

src/templates/widgets/colorpicker.html
<div id="div_id_{{field.id_for_label}}" class="form-group">
  <label for="id_{{field.id_for_label}}" class="control-label col-sm-2">
                {{field.label}}
  </label>
  <div class="controls col-sm-9">
    <input class="input-sm timeinput form-control" id="id_{{field.id_for_label}}" name="{{field.id_for_label}}" type="color" value="{{field.value}}">
  </div>
</div>

src/templates/widgets/datepicker.html
<div id="div_id_{{field.id_for_label}}" class="form-group">
  <label for="id_{{field.id_for_label}}" class="control-label col-sm-2">
                {{field.label}}
  </label>
  <div class="controls col-sm-9">
    <input class="input-sm dateinput form-control" id="id_{{field.id_for_label}}" name="{{field.id_for_label}}" type="date" value="{{field.value}}">
  </div>
</div>

src/templates/widgets/datetimepicker.html
<div id="div_id_{{field.id_for_label}}" class="form-group">
  <label for="id_{{field.id_for_label}}" class="control-label col-sm-2">
                {{field.label}}
  </label>
  <div class="controls col-sm-9">
    <input class="input-sm datetimeinput form-control" id="id_{{field.id_for_label}}" name="{{field.id_for_label}}" type="datetime-local" value="{{field.value}}">
  </div>
</div>

src/templates/widgets/timepicker.html
<div id="div_id_{{field.id_for_label}}" class="form-group">
  <label for="id_{{field.id_for_label}}" class="control-label col-sm-2">
                {{field.label}}
  </label>
  <div class="controls col-sm-9">
    <input class="input-sm timeinput form-control" id="id_{{field.id_for_label}}" name="{{field.id_for_label}}" type="time" value="{{field.value}}">
  </div>
</div>